events { }

http {
    upstream rag_api_nodes {
        # Nginx will automatically detect if a server goes down and stop sending traffic to it
        server 192.168.76.13:8001 max_fails=3 fail_timeout=30s;
        server 192.168.76.14:8001 max_fails=3 fail_timeout=30s;
        server 192.168.76.254:8001 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 8000;
        location / {
            proxy_pass http://rag_api_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}